# Generated by Django 5.1 on 2026-06-25 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaverBlogAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100)),
                ('login_pw', models.CharField(blank=True, default='', max_length=200)),
                ('blog_id', models.CharField(blank=True, default='', max_length=100)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('memo', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'naver_blog_account',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NaverKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('search_pc', models.IntegerField(default=0)),
                ('search_mobile', models.IntegerField(default=0)),
                ('search_total', models.IntegerField(default=0)),
                ('blog_count', models.IntegerField(default=0)),
                ('competition', models.CharField(blank=True, default='', max_length=20)),
                ('trend_data', models.JSONField(blank=True, null=True)),
                ('trend_period', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('last_collected', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'naver_keyword',
                'ordering': ['-priority', '-search_total'],
            },
        ),
        migrations.CreateModel(
            name='NaverBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', '초안'), ('ready', '발행대기'), ('published', '발행완료'), ('failed', '발행실패')], default='draft', max_length=20)),
                ('published_url', models.CharField(blank=True, default='', max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='naver_blog.naverblogaccount')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='naver_blog.naverkeyword')),
            ],
            options={
                'db_table': 'naver_blog_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NaverBlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='naver_blog.naverblogpost')),
            ],
            options={
                'db_table': 'naver_blog_post_image',
                'ordering': ['order'],
            },
        ),
    ]
