# Generated by Django 5.1 on 2026-06-25 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naverblogpost',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='naver_blog.naverblogaccount'),
        ),
    ]
