# Generated by Django 5.1 on 2026-06-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_blog', '0002_alter_naverblogpost_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverBlogSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=200)),
                ('naver_client_id', models.CharField(blank=True, default='', max_length=100)),
                ('naver_client_secret', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'naver_blog_setting',
            },
        ),
    ]
