# Generated by Django 5.1 on 2026-07-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_blog', '0003_naverblogsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naverblogpost',
            name='status',
            field=models.CharField(choices=[('draft', '초안'), ('ready', '발행대기'), ('naver_draft', '네이버 임시저장'), ('published', '발행완료'), ('failed', '발행실패')], default='draft', max_length=20),
        ),
    ]
