# Generated by Django 5.1 on 2026-07-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_blog', '0004_alter_naverblogpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverblogaccount',
            name='cookie_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='naverblogaccount',
            name='cookie_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
