# Generated by Django 5.1 on 2026-07-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_blog', '0005_naverblogaccount_cookie_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverblogpost',
            name='naver_log_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
