# Generated by Django 5.1 on 2026-07-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_blog', '0006_naverblogpost_naver_log_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverblogpost',
            name='naver_last_saved_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
