# Generated by Django 5.1 on 2026-07-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_blog', '0007_naverblogpost_naver_last_saved_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverblogsetting',
            name='style_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
