# Generated by Django 5.1 on 2026-07-25 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TistoryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(help_text='카카오계정 이메일 또는 티스토리 자체 로그인 ID', max_length=100)),
                ('login_pw', models.CharField(blank=True, default='', max_length=200)),
                ('blog_name', models.CharField(help_text='블로그 주소(예: myblog.tistory.com 의 myblog)', max_length=100)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('memo', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=99)),
                ('cookie_data', models.TextField(blank=True, default='')),
                ('cookie_saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tistory_account',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TistoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('draft', '초안'), ('tistory_draft', '티스토리 임시저장'), ('published', '발행완료'), ('failed', '발행실패')], default='draft', max_length=20)),
                ('tistory_post_id', models.CharField(blank=True, default='', max_length=50)),
                ('tistory_last_saved_title', models.CharField(blank=True, default='', max_length=500)),
                ('published_url', models.CharField(blank=True, default='', max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tistory_blog.tistoryaccount')),
            ],
            options={
                'db_table': 'tistory_post',
                'ordering': ['-created_at'],
            },
        ),
    ]
