# Generated by Django 5.1 on 2026-07-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteonAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100, unique=True)),
                ('login_pw', models.CharField(blank=True, default='', max_length=200)),
                ('store_name', models.CharField(blank=True, default='', max_length=100)),
                ('seller_no', models.CharField(blank=True, default='', help_text='셀러ID (예: LO10163804)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('cookie_data', models.TextField(blank=True, default='')),
                ('cookie_saved_at', models.DateTimeField(blank=True, null=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=200)),
                ('api_key_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lotteon_account',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LotteonAdCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ad_type', models.CharField(blank=True, default='', max_length=20)),
                ('cost', models.BigIntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('impression', models.IntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_costs', to='lotteon.lotteonaccount')),
            ],
            options={
                'db_table': 'lotteon_ad_cost',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account', 'date'], name='lotteon_ad__account_baf323_idx')],
                'unique_together': {('account', 'date', 'ad_type')},
            },
        ),
    ]
