# Generated by Django 5.1 on 2026-07-08 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteonMyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_no', models.CharField(db_index=True, help_text='상품번호(spdNo/pdNo)', max_length=30)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('sale_price', models.IntegerField(default=0)),
                ('status_code', models.CharField(blank=True, default='', help_text='slStatCd (SALE 등)', max_length=20)),
                ('seller_product_code', models.CharField(blank=True, default='', help_text='cmNo(판매자관리코드)', max_length=100)),
                ('category_path', models.CharField(blank=True, default='', help_text='dcatNmPath', max_length=300)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lotteon.lotteonaccount')),
            ],
            options={
                'db_table': 'lotteon_my_product',
                'indexes': [models.Index(fields=['account', 'status_code'], name='lotteon_my__account_58216f_idx')],
                'unique_together': {('account', 'pd_no')},
            },
        ),
    ]
