# Generated by Django 5.1 on 2026-07-08 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteon', '0002_lotteonmyproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteonadcost',
            name='conversion_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lotteonadcost',
            name='conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lotteonadcost',
            name='raw_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='LotteonProductAdCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('seller_item_no', models.CharField(blank=True, default='', max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('category_name', models.CharField(blank=True, default='', max_length=200)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_amount', models.BigIntegerField(default=0)),
                ('raw_json', models.TextField(blank=True, default='')),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ad_costs', to='lotteon.lotteonaccount')),
            ],
            options={
                'db_table': 'lotteon_product_ad_cost',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account', 'date'], name='lotteon_pro_account_0bb556_idx')],
                'unique_together': {('account', 'date', 'seller_item_no')},
            },
        ),
    ]
