# Generated by Django 5.1 on 2026-08-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteon', '0003_lotteonadcost_conversion_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteonmyproduct',
            name='purchase_cost',
            field=models.BigIntegerField(blank=True, help_text='예비상품(오너클랜) 마켓가 — seller_product_code(W코드) 매칭. NULL=카탈로그 미매칭', null=True),
        ),
        migrations.AlterField(
            model_name='lotteonmyproduct',
            name='seller_product_code',
            field=models.CharField(blank=True, default='', help_text='epdNo(판매자내부상품번호) — 화면 그리드 컬럼과 대조 확인(2026-08-20). cmNo는 상품별 값이 아니라 거래처 그룹코드라 오매핑이었음', max_length=100),
        ),
    ]
