# Generated by Django 5.1 on 2026-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteon', '0004_lotteonmyproduct_purchase_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteonaccount',
            name='last_check_at',
            field=models.DateTimeField(blank=True, help_text='위 값들을 마지막으로 비교한 시각', null=True),
        ),
        migrations.AddField(
            model_name='lotteonaccount',
            name='last_excel_total',
            field=models.IntegerField(blank=True, help_text='재수집 후 실제 DB 반영 건수', null=True),
        ),
        migrations.AddField(
            model_name='lotteonaccount',
            name='last_precheck_total',
            field=models.IntegerField(blank=True, help_text='크롤 시작 시 API totalCount', null=True),
        ),
    ]
