# Generated by Django 5.1 on 2026-09-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TossAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(help_text='이메일 또는 전화번호', max_length=150, unique=True)),
                ('login_pw', models.CharField(blank=True, default='', max_length=200)),
                ('seller_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('cookie_data', models.TextField(blank=True, default='')),
                ('cookie_saved_at', models.DateTimeField(blank=True, null=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'toss_account',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TossAdCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('exec_ad_cost', models.BigIntegerField(default=0, help_text='집행 광고비')),
                ('conversion_amount', models.BigIntegerField(default=0, help_text='광고 전환 거래액')),
                ('effective_roas', models.DecimalField(decimal_places=2, default=0, help_text='유효 광고 수익률(%)', max_digits=10)),
                ('impressions', models.IntegerField(default=0, help_text='노출 수')),
                ('clicks', models.IntegerField(default=0, help_text='클릭 수')),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_costs', to='toss.tossaccount')),
            ],
            options={
                'db_table': 'toss_ad_cost',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account', 'date'], name='toss_ad_cos_account_05a858_idx')],
                'unique_together': {('account', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TossCampaignAdCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('campaign_id', models.CharField(blank=True, default='', max_length=50)),
                ('campaign_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('exec_ad_cost', models.BigIntegerField(default=0)),
                ('conversion_amount', models.BigIntegerField(default=0)),
                ('effective_roas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('conv_qty', models.IntegerField(default=0)),
                ('conv_orders', models.IntegerField(default=0)),
                ('conv_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cpc', models.IntegerField(default=0)),
                ('start_date', models.CharField(blank=True, default='', max_length=20)),
                ('end_date', models.CharField(blank=True, default='', max_length=20)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_ad_costs', to='toss.tossaccount')),
            ],
            options={
                'db_table': 'toss_campaign_ad_cost',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account', 'date'], name='toss_campai_account_b5e822_idx')],
                'unique_together': {('account', 'date', 'campaign_id')},
            },
        ),
    ]
