# Generated by Django 5.1 on 2026-07-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cash', models.PositiveIntegerField(default=5000)),
                ('last_daily_claim', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('real_team', models.CharField(blank=True, max_length=20)),
                ('is_real', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('P', '투수'), ('C', '포수'), ('1B', '1루수'), ('2B', '2루수'), ('3B', '3루수'), ('SS', '유격수'), ('LF', '좌익수'), ('CF', '중견수'), ('RF', '우익수'), ('DH', '지명타자')], max_length=2)),
                ('grade', models.CharField(choices=[('common', '일반'), ('rare', '희귀'), ('hero', '영웅'), ('legend', '전설')], default='common', max_length=10)),
                ('age', models.PositiveSmallIntegerField(default=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('potential', models.PositiveSmallIntegerField(default=60)),
                ('contact', models.PositiveSmallIntegerField(default=0)),
                ('power', models.PositiveSmallIntegerField(default=0)),
                ('speed', models.PositiveSmallIntegerField(default=0)),
                ('fielding', models.PositiveSmallIntegerField(default=0)),
                ('throwing', models.PositiveSmallIntegerField(default=0)),
                ('control', models.PositiveSmallIntegerField(default=0)),
                ('velocity', models.PositiveSmallIntegerField(default=0)),
                ('stamina', models.PositiveSmallIntegerField(default=0)),
                ('breaking', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='club.team')),
            ],
        ),
    ]
