# Generated by Django 5.1 on 2026-07-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_player_year_team_league_points_team_league_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_match_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='league_tier',
            field=models.CharField(choices=[('rookie', '루키'), ('amateur', '아마추어'), ('semipro', '세미프로'), ('pro', '프로'), ('master', '마스터'), ('world', '월드'), ('super', '슈퍼')], default='rookie', max_length=10),
        ),
    ]
