# Generated by Django 5.1 on 2026-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_team_last_match_at_alter_team_league_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league_tier',
            field=models.CharField(choices=[('rookie', '루키'), ('amateur', '아마추어'), ('semipro', '세미프로'), ('pro', '프로'), ('master', '마스터'), ('world', '월드'), ('super', '슈퍼'), ('mlb', 'MLB')], default='rookie', max_length=10),
        ),
    ]
