# Generated by Django 5.1 on 2026-07-10 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_team_league_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('P', '투수'), ('C', '포수'), ('1B', '1루수'), ('2B', '2루수'), ('3B', '3루수'), ('SS', '유격수'), ('LF', '좌익수'), ('CF', '중견수'), ('RF', '우익수'), ('DH', '지명타자')], max_length=2)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_slots', to='club.team')),
            ],
            options={
                'unique_together': {('team', 'position')},
            },
        ),
    ]
