# Generated by Django 5.1 on 2026-07-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_lineupslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='home_runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pitcher_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pitcher_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rbi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(max_length=30)),
                ('win', models.BooleanField()),
                ('your_score', models.PositiveSmallIntegerField(default=0)),
                ('opp_score', models.PositiveSmallIntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_logs', to='club.team')),
            ],
        ),
    ]
