# Generated by Django 5.1 on 2026-07-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_player_hits_player_home_runs_player_pitcher_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stolen_bases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='season_matches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
