# Generated by Django 5.1 on 2026-07-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_player_era_player_hit_by_pitch_player_hits_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
