# Generated by Django 5.1 on 2026-07-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_player_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pitcher_role',
            field=models.CharField(blank=True, choices=[('SP', '선발'), ('MID', '중간계투'), ('SETUP', '셋업(홀드)'), ('CL', '마무리')], max_length=5),
        ),
    ]
