# Generated by Django 5.1 on 2026-07-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_player_pitcher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
