# Generated by Django 5.1 on 2026-07-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_player_role_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='awaken_count',
            field=models.PositiveIntegerField(default=0, help_text='전설급 재고 소진 시 각성으로 재지급된 횟수'),
        ),
        migrations.CreateModel(
            name='ChampionshipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_tier', models.CharField(choices=[('rookie', '루키'), ('amateur', '아마추어'), ('semipro', '세미프로'), ('pro', '프로'), ('master', '마스터'), ('world', '월드'), ('super', '슈퍼'), ('mlb', 'MLB')], max_length=10)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championships', to='club.team')),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
    ]
