# Generated by Django 5.1 on 2026-04-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(choices=[('naver', '네이버'), ('gmail', 'Gmail'), ('daum', '다음'), ('custom', '직접설정')], default='custom', max_length=20)),
                ('imap_host', models.CharField(max_length=200)),
                ('imap_port', models.IntegerField(default=993)),
                ('smtp_host', models.CharField(max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_accounts',
            },
        ),
        migrations.CreateModel(
            name='EmailLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6B7280', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_labels',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=500)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('folder', models.CharField(default='INBOX', max_length=100)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('from_addr', models.CharField(blank=True, max_length=300)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('to_addrs', models.JSONField(default=list)),
                ('cc_addrs', models.JSONField(blank=True, default=list)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('snippet', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('has_attachment', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='emails.emailaccount')),
            ],
            options={
                'db_table': 'email_messages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.emailmessage')),
            ],
            options={
                'db_table': 'email_attachments',
            },
        ),
        migrations.CreateModel(
            name='EmailMessageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emaillabel')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='emails.emailmessage')),
            ],
            options={
                'db_table': 'email_message_labels',
                'unique_together': {('message', 'label')},
            },
        ),
    ]
