import api from './client';

export const getCrawlerAccounts = (params?: Record<string, string>) => api.get('/cpc/crawler/accounts/', { params }).then(r => r.data);
export const createCrawlerAccount = (data: any) => api.post('/cpc/crawler/accounts/', data).then(r => r.data);
export const updateCrawlerAccount = (id: number, data: any) => api.put(`/cpc/crawler/accounts/${id}/`, data).then(r => r.data);
export const deleteCrawlerAccount = (id: number) => api.delete(`/cpc/crawler/accounts/${id}/`);
export const getCrawlerLogs = (params?: Record<string, string>) => api.get('/cpc/crawler/logs/', { params }).then(r => r.data);
export const triggerCrawl = (data: { platform: string; type: string; accounts?: string[] }) => api.post('/cpc/crawler/trigger/', data).then(r => r.data);
export const getGmarketSnapshots = (params?: Record<string, string>) => api.get('/cpc/gmarket-snapshots/', { params }).then(r => r.data);
export const getElevenCosts = (params?: Record<string, string>) => api.get('/cpc/eleven-costs/', { params }).then(r => r.data);
export const getGmarketGrades = (params?: Record<string, string>) => api.get('/cpc/gmarket-grades/', { params }).then(r => r.data);
export const getElevenGrades = (params?: Record<string, string>) => api.get('/cpc/eleven-grades/', { params }).then(r => r.data);
export const getGmarketSummary = (params?: Record<string, string>) => api.get('/cpc/gmarket-summary/', { params }).then(r => r.data);
export const getElevenSummary = (params?: Record<string, string>) => api.get('/cpc/eleven-summary/', { params }).then(r => r.data);
export const getGmarketAi = (params?: Record<string, string>) => api.get('/cpc/gmarket-ai/', { params }).then(r => r.data);
export const getSt11Campaigns = (params?: Record<string, string>) => api.get('/cpc/st11-campaigns/', { params }).then(r => r.data);

export const getCpcStatus = () => api.get('/cpc/cpc-status/').then(r => r.data);
export const getCpc2Schedule = () => api.get('/cpc/cpc2-schedule/').then(r => r.data);
export const updateCpc2Schedule = (id: number, data: any) => api.put(`/cpc/cpc2-schedule/${id}/`, data).then(r => r.data);
export const getCpc2History = () => api.get('/cpc/cpc2-history/').then(r => r.data);
export const controlCpc2 = (data: any) => api.post('/cpc/cpc2/control/', data).then(r => r.data);
export const getAiSchedule = () => api.get('/cpc/ai-schedule/').then(r => r.data);
export const updateAiSchedule = (id: number, data: any) => api.put(`/cpc/ai-schedule/${id}/`, data).then(r => r.data);
export const createAiSchedule = (data: any) => api.post('/cpc/ai-schedule/', data).then(r => r.data);
export const getTelegramConfig = () => api.get('/cpc/telegram/config/').then(r => r.data);
export const updateTelegramConfig = (id: number, data: any) => api.put(`/cpc/telegram/config/${id}/`, data).then(r => r.data);
export const createTelegramConfig = (data: any) => api.post('/cpc/telegram/config/', data).then(r => r.data);
export const getTelegramRecipients = () => api.get('/cpc/telegram/recipients/').then(r => r.data);
export const createTelegramRecipient = (data: any) => api.post('/cpc/telegram/recipients/', data).then(r => r.data);
export const deleteTelegramRecipient = (id: number) => api.delete(`/cpc/telegram/recipients/${id}/`);
export const sendTelegram = (message: string) => api.post('/cpc/telegram/send/', { message }).then(r => r.data);
export const getSellerGroups = () => api.get('/cpc/seller-groups/').then(r => r.data);
export const createSellerGroup = (data: any) => api.post('/cpc/seller-groups/', data).then(r => r.data);
export const updateSellerGroup = (id: number, data: any) => api.put(`/cpc/seller-groups/${id}/`, data).then(r => r.data);
export const deleteSellerGroup = (id: number) => api.delete(`/cpc/seller-groups/${id}/`);
