# Generated by Django 5.1 on 2026-07-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerclan', '0003_processingproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerclanApiAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100, unique=True)),
                ('login_pw', models.CharField(max_length=200)),
                ('token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_new_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ownerclan_api_account',
            },
        ),
    ]
