# Generated by Django 5.1 on 2026-07-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerclan', '0004_ownerclanapiaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerclanapiaccount',
            name='balance',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ownerclanapiaccount',
            name='info_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerclanapiaccount',
            name='lowest_price_quota',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ownerclanapiaccount',
            name='order_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ownerclanapiaccount',
            name='subscription_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
