# Generated by Django 5.1 on 2026-08-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerclan', '0005_ownerclanapiaccount_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerclanLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('checked_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ownerclan_live_status',
                'indexes': [models.Index(fields=['status'], name='ownerclan_l_status_a54d1b_idx'), models.Index(fields=['checked_at'], name='ownerclan_l_checked_e11aae_idx')],
            },
        ),
    ]
