# Generated by Django 5.1 on 2026-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerclan', '0006_ownerclanlivestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerclanOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_index=True, max_length=100)),
                ('file_type', models.CharField(choices=[('excel', '엑셀다운로드'), ('invoice', '플레이오토 송장 정보')], max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ownerclan_order_file',
                'indexes': [models.Index(fields=['login_id', 'file_type'], name='ownerclan_o_login_i_1cfa83_idx'), models.Index(fields=['downloaded_at'], name='ownerclan_o_downloa_2ac9bb_idx')],
            },
        ),
    ]
