# Generated by Django 5.1 on 2026-04-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=100, unique=True)),
                ('seller_name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('gmarket', 'Gmarket'), ('auction', 'Auction'), ('11st', '11번가'), ('coupang', '쿠팡'), ('smartstore', '스마트스토어')], default='gmarket', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seller_accounts',
                'ordering': ['display_order', 'seller_id'],
            },
        ),
    ]
