# Generated by Django 5.1 on 2026-06-24 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartStoreAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=200)),
                ('login_pw', models.CharField(blank=True, default='', max_length=200)),
                ('store_name', models.CharField(max_length=200)),
                ('store_slug', models.CharField(blank=True, default='', help_text='스토어 URL ID (네이버ID)', max_length=200)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('memo', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'smartstore_account',
                'ordering': ['display_order', 'id'],
                'unique_together': {('login_id', 'store_slug')},
            },
        ),
        migrations.CreateModel(
            name='SmartStoreCrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '실행중'), ('done', '완료'), ('error', '오류')], default='running', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_logs', to='smartstore.smartstoreaccount')),
            ],
            options={
                'db_table': 'smartstore_crawl_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartStoreAdCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ad_type', models.CharField(choices=[('shopping', '쇼핑검색'), ('click', '클릭형'), ('brand', '브랜드검색')], default='shopping', max_length=20)),
                ('cost', models.BigIntegerField(default=0)),
                ('impression', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('conversion_count', models.IntegerField(default=0)),
                ('conversion_amount', models.BigIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_costs', to='smartstore.smartstoreaccount')),
            ],
            options={
                'db_table': 'smartstore_ad_cost',
                'indexes': [models.Index(fields=['account', 'date'], name='smartstore__account_e6e4e3_idx')],
                'unique_together': {('account', 'date', 'ad_type')},
            },
        ),
        migrations.CreateModel(
            name='SmartStoreSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_count', models.IntegerField(default=0)),
                ('sales_amount', models.BigIntegerField(default=0, help_text='결제금액')),
                ('cancel_amount', models.BigIntegerField(default=0, help_text='취소금액')),
                ('return_amount', models.BigIntegerField(default=0, help_text='반품금액')),
                ('settlement_amount', models.BigIntegerField(default=0, help_text='정산예정금액')),
                ('commission_amount', models.BigIntegerField(default=0, help_text='수수료')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='smartstore.smartstoreaccount')),
            ],
            options={
                'db_table': 'smartstore_sales',
                'indexes': [models.Index(fields=['account', 'date'], name='smartstore__account_2794fa_idx')],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
