# Generated by Django 5.1 on 2026-06-24 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartStoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(help_text='originProductNo', max_length=100)),
                ('channel_product_no', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('sale_price', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('status_type', models.CharField(default='', max_length=50)),
                ('seller_management_code', models.CharField(blank=True, default='', max_length=200)),
                ('category_id', models.CharField(blank=True, default='', max_length=100)),
                ('product_image_url', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartstore.smartstoreaccount')),
            ],
            options={
                'db_table': 'smartstore_product',
                'indexes': [models.Index(fields=['account', 'status_type'], name='smartstore__account_679820_idx'), models.Index(fields=['seller_management_code'], name='smartstore__seller__2ebc74_idx')],
                'unique_together': {('account', 'product_no')},
            },
        ),
    ]
