# Generated by Django 5.1 on 2026-06-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0002_smartstoreproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartstoreaccount',
            name='commerce_api_key',
            field=models.CharField(blank=True, default='', help_text='네이버 커머스 API Client ID', max_length=200),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='commerce_secret_key',
            field=models.TextField(blank=True, default='', help_text='네이버 커머스 API Client Secret (bcrypt)'),
        ),
        migrations.AddField(
            model_name='smartstoreproduct',
            name='ownerclan_soldout',
            field=models.BooleanField(default=False, help_text='오너클랜 품절 여부 (W코드 자동처리 대상)'),
        ),
    ]
