# Generated by Django 5.1 on 2026-06-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0003_add_commerce_keys_and_ownerclan_soldout'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartstoreaccount',
            name='merchant_no',
            field=models.CharField(blank=True, default='', help_text='스마트스토어 merchantNo (GraphQL)', max_length=50),
        ),
    ]
