# Generated by Django 5.1 on 2026-06-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0004_add_merchant_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartstoreaccount',
            name='naver_ad_access_license',
            field=models.CharField(blank=True, default='', help_text='네이버 검색광고 Access License', max_length=200),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='naver_ad_customer_id',
            field=models.CharField(blank=True, default='', help_text='네이버 검색광고 Customer ID', max_length=50),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='naver_ad_secret_key',
            field=models.TextField(blank=True, default='', help_text='네이버 검색광고 Secret Key'),
        ),
    ]
