# Generated by Django 5.1 on 2026-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0005_add_naver_ad_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartstoreadcost',
            name='ad_type',
            field=models.CharField(choices=[('cpc', 'CPC(검색/클릭형)'), ('ai', 'AI(스마트쇼핑/AI추천)'), ('brand', '브랜드검색')], default='cpc', max_length=20),
        ),
    ]
