# Generated by Django 5.1 on 2026-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0006_rename_adcost_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartstoreaccount',
            name='naver_ad_ai_access_license',
            field=models.CharField(blank=True, default='', help_text='네이버 검색광고 AI Access License', max_length=200),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='naver_ad_ai_customer_id',
            field=models.CharField(blank=True, default='', help_text='네이버 검색광고 AI Customer ID', max_length=50),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='naver_ad_ai_secret_key',
            field=models.TextField(blank=True, default='', help_text='네이버 검색광고 AI Secret Key'),
        ),
        migrations.AlterField(
            model_name='smartstoreaccount',
            name='naver_ad_access_license',
            field=models.CharField(blank=True, default='', help_text='네이버 검색광고 CPC Access License', max_length=200),
        ),
        migrations.AlterField(
            model_name='smartstoreaccount',
            name='naver_ad_customer_id',
            field=models.CharField(blank=True, default='', help_text='네이버 검색광고 CPC Customer ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='smartstoreaccount',
            name='naver_ad_secret_key',
            field=models.TextField(blank=True, default='', help_text='네이버 검색광고 CPC Secret Key'),
        ),
    ]
