# Generated by Django 5.1 on 2026-06-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0008_add_purchase_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartstoreaccount',
            name='naver_ad_account_id',
            field=models.CharField(blank=True, default='', help_text='광고센터 ad-account ID (billing 스크랩용, URL의 /ad-account/숫자 부분)', max_length=50),
        ),
    ]
