# Generated by Django 5.1 on 2026-06-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0009_add_naver_ad_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartstoreaccount',
            name='naver_ad_login_id',
            field=models.CharField(blank=True, default='', help_text='광고센터 로그인 Naver ID (naver_ads_cookies.json 키와 일치)', max_length=100),
        ),
    ]
