# Generated by Django 5.1 on 2026-06-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0010_add_naver_ad_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartstoreaccount',
            name='naver_ad_ai_account_id',
            field=models.CharField(blank=True, default='', help_text='광고센터 AI ad-account ID (billing 스크랩용)', max_length=50),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='naver_ad_ai_login_id',
            field=models.CharField(blank=True, default='', help_text='광고센터 AI 로그인 Naver ID (naver_ads_cookies.json 키)', max_length=100),
        ),
        migrations.AlterField(
            model_name='smartstoreaccount',
            name='naver_ad_account_id',
            field=models.CharField(blank=True, default='', help_text='광고센터 CPC ad-account ID (billing 스크랩용)', max_length=50),
        ),
        migrations.AlterField(
            model_name='smartstoreaccount',
            name='naver_ad_login_id',
            field=models.CharField(blank=True, default='', help_text='광고센터 CPC 로그인 Naver ID (naver_ads_cookies.json 키)', max_length=100),
        ),
    ]
