# Generated by Django 5.1 on 2026-06-29 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0011_add_naver_ad_ai_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverAdProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_date', models.DateField()),
                ('until_date', models.DateField()),
                ('ad_type', models.CharField(choices=[('cpc', 'CPC(쇼핑검색)'), ('ai', 'AI(스마트쇼핑)')], default='cpc', max_length=10)),
                ('product_no', models.CharField(help_text='mallProductId', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('cost', models.BigIntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('impression', models.IntegerField(default=0)),
                ('conversion_count', models.IntegerField(default=0)),
                ('conversion_amount', models.BigIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reports', to='smartstore.smartstoreaccount')),
            ],
            options={
                'db_table': 'naver_ad_product_report',
                'indexes': [models.Index(fields=['account', 'since_date', 'until_date'], name='naver_ad_pr_account_64e174_idx'), models.Index(fields=['product_no'], name='naver_ad_pr_product_a03177_idx')],
                'unique_together': {('account', 'since_date', 'until_date', 'ad_type', 'product_no')},
            },
        ),
    ]
