# Generated by Django 5.1 on 2026-06-29 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0012_add_naver_ad_product_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartStoreCleanViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_date', models.DateField(help_text='적발일')),
                ('violation_type', models.CharField(help_text='위반사유', max_length=200)),
                ('product_name', models.CharField(help_text='상품제목', max_length=500)),
                ('product_id', models.CharField(help_text='상품번호(pid)', max_length=100)),
                ('nv_mid', models.CharField(blank=True, default='', help_text='네이버 가격비교 상품ID', max_length=100)),
                ('note', models.TextField(blank=True, default='', help_text='비고(중복상품 대표상품 정보 등)')),
                ('crawled_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_violations', to='smartstore.smartstoreaccount')),
            ],
            options={
                'db_table': 'smartstore_clean_violation',
                'ordering': ['-violation_date'],
                'indexes': [models.Index(fields=['account', 'violation_date'], name='smartstore__account_7c2355_idx'), models.Index(fields=['violation_type'], name='smartstore__violati_0408e3_idx')],
                'unique_together': {('account', 'violation_date', 'product_id')},
            },
        ),
    ]
