# Generated by Django 5.1 on 2026-07-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0013_clean_violation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverSearchTermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('keyword', models.CharField(max_length=200)),
                ('impression', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('conv_cnt', models.IntegerField(default=0)),
                ('conv_amt', models.BigIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_term_reports', to='smartstore.smartstoreaccount')),
            ],
            options={
                'db_table': 'naver_search_term_report',
                'indexes': [models.Index(fields=['account', 'ym'], name='naver_searc_account_2ab2a5_idx')],
                'unique_together': {('account', 'ym', 'keyword')},
            },
        ),
    ]
