# Generated by Django 5.1 on 2026-08-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0015_smartstoreproduct_purchase_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartstoreaccount',
            name='last_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='last_excel_selling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='last_excel_soldout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='last_excel_stopped',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='last_excel_total',
            field=models.IntegerField(blank=True, help_text='실제 DB에 반영된 상품수', null=True),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='last_precheck_selling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='last_precheck_soldout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='last_precheck_stopped',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='last_precheck_total',
            field=models.IntegerField(blank=True, help_text='상품 API totalElements(페이지1 응답)', null=True),
        ),
    ]
