# Generated by Django 5.1 on 2026-08-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0016_smartstoreaccount_last_check_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartStoreNameOptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('done', '완료'), ('skipped', '스킵')], max_length=20)),
                ('fields_updated', models.CharField(blank=True, default='', help_text='예: name,tags,notice', max_length=100)),
                ('reason', models.TextField(blank=True, default='', help_text='스킵 사유 또는 변경 요약')),
                ('old_name', models.CharField(blank=True, default='', max_length=500)),
                ('new_name', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_opt_logs', to='smartstore.smartstoreaccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_opt_logs', to='smartstore.smartstoreproduct')),
            ],
            options={
                'db_table': 'smartstore_name_opt_log',
                'indexes': [models.Index(fields=['account', 'status'], name='smartstore__account_8d3d71_idx'), models.Index(fields=['product'], name='smartstore__product_a14079_idx')],
            },
        ),
    ]
