# Generated by Django 5.1 on 2026-08-29 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0017_smartstorenameoptlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smartstorenameoptlog',
            name='smartstore__product_a14079_idx',
        ),
        migrations.AddField(
            model_name='smartstorenameoptlog',
            name='channel_product_no',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smartstorenameoptlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_opt_logs', to='smartstore.smartstoreproduct'),
        ),
        migrations.AddIndex(
            model_name='smartstorenameoptlog',
            index=models.Index(fields=['channel_product_no'], name='smartstore__channel_7632c4_idx'),
        ),
    ]
