# Generated by Django 5.1 on 2026-08-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0018_remove_smartstorenameoptlog_smartstore__product_a14079_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartstoreaccount',
            name='bizmoney_balance',
            field=models.IntegerField(blank=True, help_text='비즈머니(비즈월렛) 총 잔액(원) — ads.naver.com billing/balance 스크랩', null=True),
        ),
        migrations.AddField(
            model_name='smartstoreaccount',
            name='bizmoney_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
