# Generated by Django 5.1 on 2026-09-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0019_smartstoreaccount_bizmoney_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomeggookApiAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'domeggook_api_account',
            },
        ),
    ]
