# Generated by Django 5.1 on 2026-09-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0020_domeggookapiaccount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='naveradproductreport',
            unique_together={('account', 'since_date', 'ad_type', 'product_no')},
        ),
    ]
