# Generated by Django 5.1 on 2026-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoHistory',
            fields=[
                ('drw_no', models.IntegerField(primary_key=True, serialize=False)),
                ('drw_date', models.CharField(blank=True, default='', max_length=20)),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('num3', models.IntegerField()),
                ('num4', models.IntegerField()),
                ('num5', models.IntegerField()),
                ('num6', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lotto_history',
                'ordering': ['drw_no'],
            },
        ),
    ]
