# Generated by Django 5.1 on 2026-05-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_round', models.IntegerField(help_text='예측 대상 회차 번호')),
                ('combinations', models.JSONField(help_text='예측 조합 리스트')),
                ('score_threshold', models.IntegerField(default=0, help_text='검색에 사용된 타겟 점수')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'lotto_prediction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_round'], name='lotto_predi_target__57d9d2_idx')],
            },
        ),
    ]
