# Generated by Django 5.1 on 2026-04-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPCDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('deposited_amount', models.IntegerField(default=0)),
                ('deposit_date', models.DateField()),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpc_deposits', to='accounts.selleraccount')),
            ],
            options={
                'db_table': 'cpc_deposits',
                'ordering': ['-deposit_date'],
            },
        ),
        migrations.CreateModel(
            name='CPCTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField()),
                ('category', models.CharField(choices=[('CPC', 'CPC'), ('AI', 'AI'), ('서버이용료', '서버이용료'), ('기타', '기타')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpc_transactions', to='accounts.selleraccount')),
            ],
            options={
                'db_table': 'cpc_transactions',
                'ordering': ['-transaction_time'],
            },
        ),
        migrations.CreateModel(
            name='CPCDailyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cpc_cost', models.IntegerField(default=0)),
                ('ai_cost', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('roas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpc_daily_costs', to='accounts.selleraccount')),
            ],
            options={
                'db_table': 'cpc_daily_costs',
                'ordering': ['-date'],
                'unique_together': {('seller', 'date')},
            },
        ),
    ]
