# Generated by Django 5.1 on 2026-04-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('level', models.CharField(default='info', max_length=10)),
                ('message', models.TextField()),
                ('account_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crawler_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GmarketDepositSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmarket_id', models.CharField(max_length=50)),
                ('total_balance', models.IntegerField(default=0)),
                ('gmarket_cpc', models.IntegerField(default=0)),
                ('auction_cpc', models.IntegerField(default=0)),
                ('ai_usage', models.IntegerField(default=0)),
                ('total_usage', models.IntegerField(default=0)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gmarket_deposit_snapshots',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('gmarket', 'Gmarket'), ('11st', '11번가')], max_length=20)),
                ('login_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('seller_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('fail_count', models.IntegerField(default=0)),
                ('crawling_status', models.CharField(default='정상', max_length=20)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('cookie_data', models.TextField(blank=True)),
                ('cookie_saved_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crawler_accounts',
                'ordering': ['display_order'],
                'unique_together': {('platform', 'login_id')},
            },
        ),
        migrations.CreateModel(
            name='ElevenCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=50)),
                ('transaction_datetime', models.DateTimeField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('raw_description', models.CharField(blank=True, max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eleven_cost_history',
                'ordering': ['-transaction_datetime'],
                'unique_together': {('seller_id', 'transaction_datetime')},
            },
        ),
    ]
