# Generated by Django 5.1 on 2026-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0002_crawlerlog_gmarketdepositsnapshot_crawleraccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevenSellerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleven_id', models.CharField(max_length=50)),
                ('seller_name', models.CharField(blank=True, max_length=100)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('grade_img_src', models.CharField(blank=True, max_length=500)),
                ('required_sales', models.IntegerField(blank=True, null=True)),
                ('grade_message', models.CharField(blank=True, max_length=255)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'eleven_seller_grades',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='GmarketSellerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmarket_id', models.CharField(max_length=50)),
                ('seller_id', models.CharField(blank=True, max_length=50)),
                ('seller_grade', models.CharField(blank=True, max_length=50)),
                ('max_item_count', models.IntegerField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=50)),
                ('contact_expiry', models.CharField(blank=True, max_length=50)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gmarket_seller_grades',
                'ordering': ['-collected_at'],
            },
        ),
    ]
