# Generated by Django 5.1 on 2026-04-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0003_elevensellergrade_gmarketsellergrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawleraccount',
            name='password',
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='gmarket_origin_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='is_multi_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='password_enc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='sub_accounts',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='gmarketdepositsnapshot',
            name='ad_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmarketdepositsnapshot',
            name='card_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmarketdepositsnapshot',
            name='cash_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmarketdepositsnapshot',
            name='event_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='elevencosthistory',
            table='eleven_sellerpoint_history',
        ),
    ]
