# Generated by Django 5.1 on 2026-04-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0004_remove_crawleraccount_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketAiAdHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmarket_id', models.CharField(max_length=50)),
                ('seller_id', models.CharField(max_length=50)),
                ('group_name', models.CharField(blank=True, max_length=200)),
                ('event_time', models.DateTimeField()),
                ('history_type', models.CharField(blank=True, max_length=100)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gmarket_ai_ad_history',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='GmarketAiAdSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmarket_id', models.CharField(max_length=50)),
                ('seller_id', models.CharField(max_length=50)),
                ('group_name', models.CharField(blank=True, max_length=200)),
                ('button_status', models.CharField(default='OFF', max_length=10)),
                ('actual_status', models.CharField(default='OFF', max_length=10)),
                ('actual_reason', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=20)),
                ('end_date', models.CharField(blank=True, max_length=20)),
                ('operation_status', models.CharField(blank=True, max_length=200)),
                ('budget_mgmt', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gmarket_ai_ad_summary',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='St11AiAdHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=50)),
                ('action', models.CharField(blank=True, max_length=20)),
                ('campaign_name', models.CharField(blank=True, max_length=200)),
                ('before_status', models.CharField(blank=True, max_length=10)),
                ('after_status', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'st11_ai_ad_history',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='St11AdofficeCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleven_id', models.CharField(max_length=50)),
                ('campaign_name', models.CharField(max_length=200)),
                ('is_ai', models.BooleanField(default=False)),
                ('onoff', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('daily_budget', models.IntegerField(blank=True, null=True)),
                ('target_roas', models.IntegerField(blank=True, null=True)),
                ('exposure_period', models.CharField(blank=True, max_length=100)),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('avg_rank', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avg_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.IntegerField(blank=True, null=True)),
                ('total_conversions', models.IntegerField(blank=True, null=True)),
                ('cost_per_conversion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_conv_amount', models.IntegerField(blank=True, null=True)),
                ('total_conv_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('total_roas_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('direct_conversions', models.IntegerField(blank=True, null=True)),
                ('direct_conv_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('direct_conv_amount', models.IntegerField(blank=True, null=True)),
                ('direct_cost_per_conv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('direct_roas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('indirect_conversions', models.IntegerField(blank=True, null=True)),
                ('indirect_cost_per_conv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('indirect_conv_amount', models.IntegerField(blank=True, null=True)),
                ('indirect_conv_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('indirect_roas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('campaign_registered_at', models.CharField(blank=True, max_length=50)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'st11_adoffice_campaign',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['eleven_id'], name='st11_adoffi_eleven__acf8e6_idx'), models.Index(fields=['collected_at'], name='st11_adoffi_collect_a3d408_idx')],
            },
        ),
    ]
