# Generated by Django 5.1 on 2026-04-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0005_gmarketaiadhistory_gmarketaiadsummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpc2History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmarket_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=5)),
                ('cpc2_before', models.IntegerField(default=0)),
                ('cpc2_after', models.IntegerField(default=0)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gmarket_cpc2_history',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='Cpc2Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_time', models.TimeField(blank=True, null=True)),
                ('off_time', models.TimeField(blank=True, null=True)),
                ('skip_holidays', models.BooleanField(default=True)),
                ('selected_accounts', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gmarket_cpc2_schedule',
            },
        ),
        migrations.CreateModel(
            name='CppBidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmarket_id', models.CharField(max_length=50)),
                ('keyword_count', models.IntegerField(default=0)),
                ('bid_start_date', models.DateField(blank=True, null=True)),
                ('bid_end_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gmarket_cpp_bid_history',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='CppSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('weekday_num', models.IntegerField(default=3)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gmarket_cpp_schedule',
            },
        ),
        migrations.CreateModel(
            name='GmarketCpcAdStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmarket_id', models.CharField(max_length=50, unique=True)),
                ('cpc1_on', models.IntegerField(default=0)),
                ('cpc1_off', models.IntegerField(default=0)),
                ('cpc2_on', models.IntegerField(default=0)),
                ('cpc2_off', models.IntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gmarket_cpc_ad_status',
            },
        ),
        migrations.CreateModel(
            name='SellerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='집중', max_length=100)),
                ('seller_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seller_groups',
            },
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('off', 'OFF'), ('change', '변동감지'), ('15m', '15분'), ('1h', '1시간')], default='off', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telegram_config',
            },
        ),
        migrations.CreateModel(
            name='TelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_send', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telegram_recipients',
            },
        ),
        migrations.CreateModel(
            name='AiSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('gmarket', 'Gmarket'), ('11st', '11번가')], max_length=20)),
                ('on_time', models.TimeField(blank=True, null=True)),
                ('off_time', models.TimeField(blank=True, null=True)),
                ('skip_holidays', models.BooleanField(default=True)),
                ('selected_accounts', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_schedule',
                'unique_together': {('platform',)},
            },
        ),
    ]
