# Generated by Django 5.1 on 2026-04-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0006_cpc2history_cpc2schedule_cppbidhistory_cppschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=200)),
                ('cron_expr', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cron_schedules',
                'ordering': ['name'],
            },
        ),
    ]
