# Generated by Django 5.1 on 2026-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0007_cronschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedSmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csphone_number', models.CharField(blank=True, max_length=20)),
                ('checkphone_number', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('setting_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'received_sms_message',
                'ordering': ['-received_at'],
            },
        ),
    ]
