# Generated by Django 5.1 on 2026-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0008_receivedsmsmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsPhoneSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sms_phone_settings',
                'ordering': ['phone_number'],
            },
        ),
    ]
