# Generated by Django 5.1 on 2026-04-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0009_smsphonesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='custom_holidays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='enabled_holidays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='off_on_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
