# Generated by Django 5.1 on 2026-04-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0010_add_ai_schedule_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='cost_type',
            field=models.CharField(choices=[('sellerpoint', '셀러포인트'), ('sellercash', '셀러캐시')], default='sellerpoint', max_length=20),
        ),
    ]
