# Generated by Django 5.1 on 2026-04-11 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0011_crawleraccount_cost_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsDeviceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sms_device_heartbeat',
            },
        ),
        migrations.CreateModel(
            name='SmsOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('sender_phone', models.CharField(blank=True, max_length=20)),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed')], default='pending', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sms_outbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='receivedsmsmessage',
            name='msg_type',
            field=models.CharField(default='SMS', max_length=10),
        ),
        migrations.AddField(
            model_name='receivedsmsmessage',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SmsMessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('filepath', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cpc.receivedsmsmessage')),
            ],
            options={
                'db_table': 'sms_message_image',
            },
        ),
    ]
