# Generated by Django 5.1 on 2026-04-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0012_smsdeviceheartbeat_smsoutbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedsmsmessage',
            name='device_sms_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
