# Generated by Django 5.1 on 2026-05-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0013_receivedsmsmessage_device_sms_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='is_focused',
            field=models.BooleanField(default=False, help_text='집중관리 대상 표시'),
        ),
    ]
