# Generated by Django 5.1 on 2026-05-09 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0014_crawleraccount_is_focused'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='11번가 셀러 OpenAPI 키', max_length=200),
        ),
        migrations.CreateModel(
            name='ElevenMyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.BigIntegerField(db_index=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('sale_price', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('status_type', models.CharField(blank=True, default='', max_length=20)),
                ('seller_product_code', models.CharField(blank=True, default='', max_length=100)),
                ('category_id', models.CharField(blank=True, default='', max_length=50)),
                ('product_image_url', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleven_my_products', to='cpc.crawleraccount')),
            ],
            options={
                'db_table': 'eleven_my_product',
                'indexes': [models.Index(fields=['account', 'status_type'], name='eleven_my_p_account_803e36_idx'), models.Index(fields=['synced_at'], name='eleven_my_p_synced__362c87_idx')],
                'unique_together': {('account', 'product_no')},
            },
        ),
    ]
