# Generated by Django 5.1 on 2026-05-10 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0015_crawleraccount_api_key_elevenmyproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevenSellerOfficeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('ad_balance', models.IntegerField(default=0)),
                ('product_limit', models.IntegerField(default=0)),
                ('products', models.IntegerField(default=0)),
                ('banned', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('overdue', models.IntegerField(default=0)),
                ('undelivered', models.IntegerField(default=0)),
                ('draft', models.IntegerField(default=0)),
                ('fulfillment', models.CharField(blank=True, default='', max_length=50)),
                ('shipping', models.CharField(blank=True, default='', max_length=50)),
                ('inquiry', models.CharField(blank=True, default='', max_length=50)),
                ('error', models.TextField(blank=True, default='')),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_stats', to='cpc.crawleraccount')),
            ],
            options={
                'db_table': 'eleven_seller_office_stat',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['account', '-collected_at'], name='eleven_sell_account_30ca62_idx')],
            },
        ),
    ]
