# Generated by Django 5.1 on 2026-06-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0016_elevensellerofficestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='connect_fail_count',
            field=models.IntegerField(default=0, help_text='연속 접속(로그인) 실패 횟수 - 3회 도달 시 실패 표시'),
        ),
    ]
