# Generated by Django 5.1 on 2026-06-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0017_crawleraccount_connect_fail_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elevencosthistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='elevencosthistory',
            name='seq',
            field=models.IntegerField(default=0, help_text='같은 거래시각 내 순번 (같은 초 다중 거래 구분)'),
        ),
        migrations.AlterUniqueTogether(
            name='elevencosthistory',
            unique_together={('seller_id', 'transaction_datetime', 'seq')},
        ),
    ]
