# Generated by Django 5.1 on 2026-06-06 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0018_alter_elevencosthistory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_short', models.CharField(max_length=100)),
                ('name_official', models.CharField(blank=True, default='', max_length=200)),
                ('biz_reg_no', models.CharField(blank=True, default='', max_length=20)),
                ('biz_type', models.CharField(choices=[('개인', '개인'), ('법인', '법인')], default='개인', max_length=10)),
                ('report_cycle', models.CharField(choices=[('월', '월'), ('분기', '분기')], default='월', max_length=10)),
                ('vat_number', models.CharField(blank=True, default='', max_length=40)),
                ('memo', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tax_business',
                'ordering': ['biz_type', 'name_short'],
            },
        ),
        migrations.CreateModel(
            name='TaxAccountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='11st', max_length=20)),
                ('login_id', models.CharField(max_length=100)),
                ('account_name', models.CharField(blank=True, default='', max_length=100)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='cpc.taxbusiness')),
            ],
            options={
                'db_table': 'tax_account_map',
                'unique_together': {('platform', 'login_id')},
            },
        ),
        migrations.CreateModel(
            name='TaxPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='11st', max_length=20)),
                ('login_id', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('source', models.CharField(default='ad', max_length=20)),
                ('supply_amount', models.BigIntegerField(default=0)),
                ('vat_amount', models.BigIntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='cpc.taxbusiness')),
            ],
            options={
                'db_table': 'tax_purchase',
                'ordering': ['-year', '-month'],
                'unique_together': {('platform', 'login_id', 'year', 'month', 'source')},
            },
        ),
        migrations.CreateModel(
            name='TaxVatMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='11st', max_length=20)),
                ('login_id', models.CharField(max_length=100)),
                ('seller_name', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('taxable_sales', models.BigIntegerField(default=0)),
                ('tax_free_sales', models.BigIntegerField(default=0)),
                ('zero_rate_sales', models.BigIntegerField(default=0)),
                ('credit_card', models.BigIntegerField(default=0)),
                ('cash_receipt', models.BigIntegerField(default=0)),
                ('expense_proof', models.BigIntegerField(default=0)),
                ('mobile', models.BigIntegerField(default=0)),
                ('etc_amount', models.BigIntegerField(default=0)),
                ('extra_fee', models.BigIntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_monthly', to='cpc.taxbusiness')),
            ],
            options={
                'db_table': 'tax_vat_monthly',
                'ordering': ['-year', '-month'],
                'unique_together': {('platform', 'login_id', 'year', 'month')},
            },
        ),
    ]
