# Generated by Django 5.1 on 2026-06-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0019_taxbusiness_taxaccountmap_taxpurchase_taxvatmonthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='last_otp_at',
            field=models.DateTimeField(blank=True, help_text='마지막 OTP 인증 완료 시각 (11번가 OTP는 24시간 유지)', null=True),
        ),
    ]
