# Generated by Django 5.1 on 2026-06-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0020_crawleraccount_last_otp_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='St11ProductRoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleven_id', models.CharField(max_length=50)),
                ('product_no', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=20)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conv_amount', models.BigIntegerField(default=0)),
                ('roas_pct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('keyword_count', models.IntegerField(default=0)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'st11_product_roas',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['eleven_id', 'period'], name='st11_produc_eleven__9e2333_idx'), models.Index(fields=['collected_at'], name='st11_produc_collect_0895c0_idx')],
            },
        ),
    ]
