# Generated by Django 5.1 on 2026-06-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0021_st11productroas'),
    ]

    operations = [
        migrations.CreateModel(
            name='St11ProductDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleven_id', models.CharField(max_length=50)),
                ('product_no', models.CharField(max_length=50)),
                ('stat_date', models.DateField()),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conv_amount', models.BigIntegerField(default=0)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'st11_product_daily',
                'ordering': ['-stat_date'],
                'indexes': [models.Index(fields=['eleven_id', 'stat_date'], name='st11_produc_eleven__426f21_idx'), models.Index(fields=['stat_date'], name='st11_produc_stat_da_eb15f8_idx')],
                'constraints': [models.UniqueConstraint(fields=('eleven_id', 'product_no', 'stat_date'), name='uniq_eleven_product_day')],
            },
        ),
    ]
