# Generated by Django 5.1 on 2026-06-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0022_st11productdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='St11KeywordDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleven_id', models.CharField(max_length=50)),
                ('product_no', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=255)),
                ('stat_date', models.DateField()),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conv_amount', models.BigIntegerField(default=0)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'st11_keyword_daily',
                'ordering': ['-stat_date'],
                'indexes': [models.Index(fields=['eleven_id', 'stat_date'], name='st11_keywor_eleven__843f91_idx'), models.Index(fields=['stat_date'], name='st11_keywor_stat_da_a3d653_idx')],
            },
        ),
    ]
