# Generated by Django 5.1 on 2026-06-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0023_st11keyworddaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='St11LossDeleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleven_id', models.CharField(max_length=50)),
                ('product_no', models.CharField(max_length=50)),
                ('seller_code', models.CharField(blank=True, default='', max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'st11_loss_deleted',
                'indexes': [models.Index(fields=['eleven_id', 'product_no'], name='st11_loss_d_eleven__9d7c54_idx')],
                'unique_together': {('eleven_id', 'product_no')},
            },
        ),
    ]
