# Generated by Django 5.1 on 2026-06-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0024_st11lossdeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketMyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(default='gmarket', max_length=10)),
                ('product_no', models.CharField(db_index=True, max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('sale_price', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('status_type', models.CharField(blank=True, default='', max_length=20)),
                ('seller_product_code', models.CharField(blank=True, default='', max_length=100)),
                ('category_code', models.CharField(blank=True, default='', max_length=50)),
                ('product_image_url', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmarket_my_products', to='cpc.crawleraccount')),
            ],
            options={
                'db_table': 'gmarket_my_product',
                'indexes': [models.Index(fields=['account', 'status_type'], name='gmarket_my__account_3cff04_idx'), models.Index(fields=['product_no'], name='gmarket_my__product_55a244_idx'), models.Index(fields=['synced_at'], name='gmarket_my__synced__bd2995_idx')],
                'unique_together': {('account', 'market', 'product_no')},
            },
        ),
    ]
