# Generated by Django 5.1 on 2026-06-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0025_gmarketmyproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(db_index=True, max_length=50)),
                ('use_date', models.DateField(db_index=True)),
                ('seq', models.IntegerField(default=0)),
                ('use_type', models.CharField(blank=True, default='', max_length=20)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.BigIntegerField(default=0)),
                ('related_no', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gmarket_cost_history',
                'ordering': ['-use_date', 'seq'],
                'indexes': [models.Index(fields=['seller_id', 'use_date'], name='gmarket_cos_seller__727d87_idx'), models.Index(fields=['transaction_type'], name='gmarket_cos_transac_f9b4e1_idx')],
                'unique_together': {('seller_id', 'use_date', 'seq')},
            },
        ),
    ]
