# Generated by Django 5.1 on 2026-06-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0026_gmarketcosthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketAdGroupPerf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmarket_id', models.CharField(db_index=True, max_length=50)),
                ('ad_type', models.CharField(choices=[('normal', '일반광고'), ('smart', '간편광고')], default='normal', max_length=10)),
                ('stat_date', models.DateField(db_index=True)),
                ('ad_group_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('ad_on', models.IntegerField(default=0)),
                ('ad_off', models.IntegerField(default=0)),
                ('avg_rank', models.CharField(blank=True, default='', max_length=20)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_click_cost', models.BigIntegerField(default=0)),
                ('total_cost', models.BigIntegerField(default=0)),
                ('daily_budget', models.CharField(blank=True, default='', max_length=50)),
                ('product_count', models.CharField(blank=True, default='', max_length=50)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gmarket_adgroup_perf',
                'ordering': ['-stat_date', 'gmarket_id'],
                'indexes': [models.Index(fields=['gmarket_id', 'stat_date'], name='gmarket_adg_gmarket_6fd236_idx'), models.Index(fields=['collected_at'], name='gmarket_adg_collect_557159_idx')],
                'unique_together': {('gmarket_id', 'ad_type', 'stat_date', 'ad_group_name')},
            },
        ),
    ]
