# Generated by Django 5.1 on 2026-06-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0027_gmarketadgroupperf'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gmarketcosthistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gmarketcosthistory',
            name='market',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='gmarketcosthistory',
            unique_together={('seller_id', 'market', 'use_date', 'seq')},
        ),
        migrations.AddIndex(
            model_name='gmarketcosthistory',
            index=models.Index(fields=['market', 'use_date'], name='gmarket_cos_market_36696e_idx'),
        ),
    ]
