# Generated by Django 5.1 on 2026-06-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0028_alter_gmarketcosthistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmarketcosthistory',
            name='traded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
