# Generated by Django 5.1 on 2026-06-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0029_gmarketcosthistory_traded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketProductAdCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_index=True, max_length=50)),
                ('seller_id', models.CharField(blank=True, default='', max_length=50)),
                ('ad_type', models.CharField(choices=[('cpc', 'CPC'), ('ai', 'AI매출업')], db_index=True, max_length=4)),
                ('product_no', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('site', models.CharField(blank=True, default='', max_length=10)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('avg_click_cost', models.BigIntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('conv_amount', models.BigIntegerField(default=0)),
                ('conv_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('roas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gmarket_product_adcost',
                'ordering': ['-year', '-month', 'login_id', '-cost'],
                'indexes': [models.Index(fields=['login_id', 'ad_type', 'year', 'month'], name='gmarket_pro_login_i_d7598a_idx'), models.Index(fields=['product_no'], name='gmarket_pro_product_cc5173_idx'), models.Index(fields=['year', 'month', 'ad_type'], name='gmarket_pro_year_c3aa17_idx')],
                'unique_together': {('login_id', 'ad_type', 'product_no', 'year', 'month')},
            },
        ),
    ]
