# Generated by Django 5.1 on 2026-06-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0030_gmarketproductadcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketLossDeleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=50)),
                ('product_no', models.CharField(max_length=50)),
                ('seller_code', models.CharField(blank=True, default='', max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gmarket_loss_deleted',
                'indexes': [models.Index(fields=['login_id', 'product_no'], name='gmarket_los_login_i_dc63f9_idx')],
                'unique_together': {('login_id', 'product_no')},
            },
        ),
    ]
