# Generated by Django 5.1 on 2026-06-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0031_gmarketlossdeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketKeywordReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_index=True, max_length=50)),
                ('seller_id', models.CharField(blank=True, default='', max_length=50)),
                ('product_no', models.CharField(db_index=True, max_length=50)),
                ('keyword', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('click_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_rank', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_click_cost', models.BigIntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('conv_amount', models.BigIntegerField(default=0)),
                ('conv_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('roas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gmarket_keyword_report',
                'ordering': ['-year', '-month', 'login_id', '-cost'],
                'indexes': [models.Index(fields=['login_id', 'year', 'month'], name='gmarket_key_login_i_64128e_idx'), models.Index(fields=['product_no'], name='gmarket_key_product_52a0a2_idx'), models.Index(fields=['year', 'month'], name='gmarket_key_year_5794ac_idx')],
                'unique_together': {('login_id', 'product_no', 'keyword', 'year', 'month')},
            },
        ),
    ]
