# Generated by Django 5.1 on 2026-06-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0032_gmarketkeywordreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCodeArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('login_id', models.CharField(blank=True, default='', max_length=100)),
                ('product_no', models.CharField(db_index=True, max_length=50)),
                ('seller_code', models.CharField(blank=True, default='', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_code_archive',
                'indexes': [models.Index(fields=['platform', 'product_no'], name='product_cod_platfor_00e3f0_idx'), models.Index(fields=['seller_code'], name='product_cod_seller__cd1c44_idx')],
                'unique_together': {('platform', 'product_no')},
            },
        ),
    ]
