# Generated by Django 5.1 on 2026-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0033_productcodearchive'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crawlerlog',
            index=models.Index(fields=['-created_at'], name='crawler_log_created_be38b3_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlerlog',
            index=models.Index(fields=['platform', 'level', '-created_at'], name='crawler_log_platfor_127e81_idx'),
        ),
        migrations.AddIndex(
            model_name='elevencosthistory',
            index=models.Index(fields=['transaction_type', 'transaction_datetime'], name='eleven_sell_transac_55cee8_idx'),
        ),
        migrations.AddIndex(
            model_name='gmarketdepositsnapshot',
            index=models.Index(fields=['gmarket_id', '-collected_at'], name='gmarket_dep_gmarket_b182cb_idx'),
        ),
        migrations.AddIndex(
            model_name='gmarketmyproduct',
            index=models.Index(fields=['account', 'seller_product_code', 'id'], name='gmkt_my_dedup_idx'),
        ),
        migrations.AddIndex(
            model_name='st11productdaily',
            index=models.Index(fields=['stat_date', 'eleven_id', 'product_no', 'cost', 'conv_amount'], name='st11pd_month_cover_idx'),
        ),
    ]
