# Generated by Django 5.1 on 2026-06-14 15:42

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0034_crawlerlog_crawler_log_created_be38b3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevenmyproduct',
            name='purchase_cost',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='elevenmyproduct',
            name='cost_diff',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('sale_price'), '-', models.F('purchase_cost')), output_field=models.IntegerField()),
        ),
    ]
