# Generated by Django 5.1 on 2026-06-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0035_elevenmyproduct_purchase_cost_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='elevenmyproduct',
            index=models.Index(fields=['seller_product_code'], name='eleven_my_p_seller__5ee14e_idx'),
        ),
    ]
