# Generated by Django 5.1 on 2026-06-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0036_elevenmyproduct_eleven_my_p_seller__5ee14e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='St11AdStrategyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=40)),
                ('eleven_id', models.CharField(blank=True, max_length=50)),
                ('campaign_name', models.CharField(blank=True, max_length=200)),
                ('group_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'st11_ad_strategy_log',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['run_id'], name='st11_ad_str_run_id_48912d_idx'), models.Index(fields=['created_at'], name='st11_ad_str_created_2022f4_idx')],
            },
        ),
    ]
