# Generated by Django 5.1 on 2026-06-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0037_st11adstrategylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cpc2schedule',
            name='weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
