# Generated by Django 5.1 on 2026-06-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0038_aischedule_weekdays_cpc2schedule_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='off_weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cpc2schedule',
            name='off_weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
