# Generated by Django 5.1 on 2026-06-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0039_aischedule_off_weekdays_cpc2schedule_off_weekdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='St11AdStrategySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='기본 전략', max_length=100)),
                ('accounts', models.JSONField(blank=True, default=list)),
                ('campaigns', models.JSONField(blank=True, default=list)),
                ('on_start', models.IntegerField(default=8)),
                ('on_end', models.IntegerField(default=16)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=False)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'st11_ad_strategy_schedule',
                'ordering': ['-updated_at'],
            },
        ),
    ]
