# Generated by Django 5.1 on 2026-06-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0040_st11adstrategyschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpc2schedule',
            name='include_cpc1',
            field=models.BooleanField(default=False),
        ),
    ]
