# Generated by Django 5.1 on 2026-06-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0041_cpc2schedule_include_cpc1'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='auction_seller_id',
            field=models.CharField(blank=True, help_text='ESM 옥션 seller_id (지마켓 login_id와 다를 때만 설정 — 예: rejoice666→rejoice7942)', max_length=50, null=True),
        ),
    ]
