# Generated by Django 5.1 on 2026-07-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0042_add_auction_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='hide_from_dashboard',
            field=models.BooleanField(default=False, help_text='지마켓/옥션 대시보드 계정목록에서 숨김(ROAS 등 리포트에는 계속 표시) — 타사 테스트 계정용'),
        ),
    ]
