# Generated by Django 5.1 on 2026-07-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0043_crawleraccount_hide_from_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='is_test_account',
            field=models.BooleanField(default=False, help_text='테스트/타사 계정 — 조회·다운로드만 허용, 판매중지·삭제·광고on/off 등 실제 조치는 전부 차단'),
        ),
    ]
