# Generated by Django 5.1 on 2026-08-19 07:02

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0044_add_is_test_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmarketmyproduct',
            name='purchase_cost',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gmarketmyproduct',
            name='cost_diff',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('sale_price'), '-', models.F('purchase_cost')), output_field=models.IntegerField()),
        ),
    ]
