# Generated by Django 5.1 on 2026-08-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0045_gmarketmyproduct_purchase_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('checked_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'l_code_status',
                'indexes': [models.Index(fields=['status'], name='l_code_stat_status_d59f52_idx'), models.Index(fields=['checked_at'], name='l_code_stat_checked_7a93ed_idx')],
            },
        ),
    ]
