# Generated by Django 5.1 on 2026-08-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0046_lcodestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketManualCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(db_index=True, max_length=50)),
                ('use_date', models.DateField(db_index=True)),
                ('amount', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, default='바이럴', max_length=100)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gmarket_manual_cost',
                'ordering': ['-use_date', '-id'],
                'indexes': [models.Index(fields=['seller_id', 'use_date'], name='gmarket_man_seller__ad73bd_idx')],
            },
        ),
    ]
