# Generated by Django 5.1 on 2026-08-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0047_gmarketmanualcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='last_check_at',
            field=models.DateTimeField(blank=True, help_text='위 두 값을 마지막으로 비교/기록한 시각', null=True),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='last_excel_total',
            field=models.IntegerField(blank=True, help_text='엑셀 다운로드/파싱으로 실제 반영된 상품수', null=True),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='last_precheck_total',
            field=models.IntegerField(blank=True, help_text='크롤 시작 시 전체상품수 탭에서 읽은 값', null=True),
        ),
    ]
