# Generated by Django 5.1 on 2026-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0048_crawleraccount_last_check_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='last_excel_selling',
            field=models.IntegerField(blank=True, help_text='엑셀 반영 후 DB 판매중 건수', null=True),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='last_excel_soldout',
            field=models.IntegerField(blank=True, help_text='엑셀 반영 후 DB 품절 건수', null=True),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='last_excel_stopped',
            field=models.IntegerField(blank=True, help_text='엑셀 반영 후 DB 판매중지 건수', null=True),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='last_precheck_selling',
            field=models.IntegerField(blank=True, help_text='크롤 시작 시 판매중 탭 값', null=True),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='last_precheck_soldout',
            field=models.IntegerField(blank=True, help_text='크롤 시작 시 품절 탭 값', null=True),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='last_precheck_stopped',
            field=models.IntegerField(blank=True, help_text='크롤 시작 시 판매중지 탭 값', null=True),
        ),
        migrations.AlterField(
            model_name='crawleraccount',
            name='last_check_at',
            field=models.DateTimeField(blank=True, help_text='위 값들을 마지막으로 비교/기록한 시각', null=True),
        ),
    ]
