# Generated by Django 5.1 on 2026-08-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0049_crawleraccount_last_excel_selling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcodestatus',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
