# Generated by Django 5.1 on 2026-08-28 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0050_lcodestatus_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketSalePeriodStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(db_index=True, max_length=50)),
                ('goods_no', models.CharField(blank=True, default='', max_length=50)),
                ('disp_end_date', models.CharField(blank=True, default='', max_length=30)),
                ('discount_type', models.IntegerField(blank=True, null=True)),
                ('discount_amt', models.IntegerField(blank=True, null=True)),
                ('needs_fix', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmarket_saleperiod_status', to='cpc.crawleraccount')),
            ],
            options={
                'db_table': 'gmarket_saleperiod_status',
                'indexes': [models.Index(fields=['needs_fix'], name='gmarket_sal_needs_f_57e177_idx'), models.Index(fields=['disp_end_date'], name='gmarket_sal_disp_en_75cd9d_idx'), models.Index(fields=['checked_at'], name='gmarket_sal_checked_22502b_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'product_no'), name='uniq_gmkt_saleperiod_acct_pno')],
            },
        ),
    ]
