# Generated by Django 5.1 on 2026-09-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0051_gmarketsaleperiodstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevencosthistory',
            name='valid_until',
            field=models.DateField(blank=True, help_text='포인트/캐시 유효기간(사용기한) — 원본 엑셀 "유효기간" 컬럼, 없으면 null', null=True),
        ),
    ]
