# Generated by Django 5.1 on 2026-09-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0052_elevencosthistory_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevencosthistory',
            name='cost_type',
            field=models.CharField(choices=[('sellerpoint', '셀러포인트'), ('sellercash', '셀러캐시')], default='sellerpoint', help_text='포인트/캐시는 별도 잔액 풀 — 만료건 선입선출 잔액계산 시 풀 섞임 방지용', max_length=20),
        ),
    ]
