# Generated by Django 5.1 on 2026-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0053_elevencosthistory_cost_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('label', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'overview_expense_item',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='overview_ex_date_59d300_idx')],
            },
        ),
    ]
