# Generated by Django 5.1 on 2026-09-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0054_overviewexpenseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAdCenterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmarket_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=5)),
                ('campaign_before', models.IntegerField(default=0)),
                ('campaign_after', models.IntegerField(default=0)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gmarket_new_adcenter_history',
                'ordering': ['-event_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='cpc2history',
            options={},
        ),
    ]
