# Generated by Django 5.1 on 2026-09-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0055_newadcenterhistory_alter_cpc2history_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aischedule',
            name='off_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aischedule',
            name='on_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
