# Generated by Django 5.1 on 2026-09-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0056_ai_schedule_on_off_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='last_real_otp_at',
            field=models.DateTimeField(blank=True, help_text='11번가가 실제로 OTP 인증번호 입력을 요구해서 통과한 시각만 기록(세션/기기인식 스킵은 제외) — 대시보드 "인증 필요" 판정은 이 필드 기준', null=True),
        ),
        migrations.AlterField(
            model_name='crawleraccount',
            name='last_otp_at',
            field=models.DateTimeField(blank=True, help_text='마지막 로그인 성공 시각(OTP 실제입력/세션스킵 구분없이 갱신 — 쿠키세션 유효성 판단용, 대시보드 인증현황엔 쓰지 말것)', null=True),
        ),
    ]
