# Generated by Django 5.1 on 2026-09-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0057_crawleraccount_last_real_otp_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAdCenterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_time', models.TimeField(blank=True, null=True)),
                ('off_time', models.TimeField(blank=True, null=True)),
                ('selected_accounts', models.JSONField(blank=True, default=list)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('off_weekdays', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gmarket_new_adcenter_schedule',
            },
        ),
    ]
