# Generated by Django 5.1 on 2026-09-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0058_newadcenterschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketNewAdCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_index=True, max_length=50)),
                ('use_date', models.DateField(db_index=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(blank=True, default='', max_length=32)),
                ('is_ai', models.BooleanField(default=False)),
                ('cost', models.IntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gmarket_new_ad_cost',
                'indexes': [models.Index(fields=['login_id', 'use_date'], name='gmarket_new_login_i_9cffac_idx')],
                'constraints': [models.UniqueConstraint(fields=('login_id', 'use_date', 'campaign_name'), name='uniq_newadcost_login_date_campaign')],
            },
        ),
    ]
