# Generated by Django 5.1 on 2026-09-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0059_gmarketnewadcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmarketdepositsnapshot',
            name='auction_ai_usage',
            field=models.IntegerField(default=0),
        ),
    ]
