# Generated by Django 5.1 on 2026-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0060_gmarketdepositsnapshot_auction_ai_usage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='elevencosthistory',
            index=models.Index(fields=['transaction_datetime'], name='eleven_sph_txn_dt_idx'),
        ),
    ]
