# Generated by Django 5.1 on 2026-09-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0061_elevencosthistory_eleven_sph_txn_dt_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmarketnewadcost',
            name='conv_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmarketnewadcost',
            name='roas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
