# Generated by Django 5.1 on 2026-09-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0062_gmarketnewadcost_conv_amount_gmarketnewadcost_roas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomemartAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(default='rejoice888', max_length=50, unique=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('order_stats', models.JSONField(blank=True, default=dict)),
                ('info_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domemart_account_info',
            },
        ),
    ]
