# Generated by Django 5.1 on 2026-09-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0063_domemartaccountinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomemartOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(default='rejoice888', max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('row_count', models.IntegerField(default=0)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'domemart_order_file',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
