# Generated by Django 5.1.15 on 2026-09-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0064_domemartorderfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleraccount',
            name='last_product_daily_check_at',
            field=models.DateTimeField(blank=True, help_text='상품일별(St11ProductDaily) 마지막 정상 확인 시각(0건 확인도 포함, 실패시 갱신 안 됨)', null=True),
        ),
        migrations.AddField(
            model_name='crawleraccount',
            name='last_product_roas_check_at',
            field=models.DateTimeField(blank=True, help_text='상품ROAS(St11ProductRoas) 마지막 정상 확인 시각(0건 확인도 포함, 실패시 갱신 안 됨)', null=True),
        ),
    ]
