# Generated by Django 5.1.15 on 2026-09-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0065_crawleraccount_last_product_daily_check_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketNewAdProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_index=True, max_length=50)),
                ('use_date', models.DateField(db_index=True)),
                ('product_no', models.CharField(db_index=True, max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('avg_click_cost', models.BigIntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('conv_amount', models.BigIntegerField(default=0)),
                ('conv_count', models.IntegerField(default=0)),
                ('roas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gmarket_newad_product_cost',
                'indexes': [models.Index(fields=['login_id', 'use_date'], name='gmarket_new_login_i_8bacf9_idx'), models.Index(fields=['product_no'], name='gmarket_new_product_636e93_idx')],
                'constraints': [models.UniqueConstraint(fields=('login_id', 'use_date', 'product_no'), name='uniq_newad_product_cost_login_date_product')],
            },
        ),
    ]
