# Generated by Django 5.1.15 on 2026-09-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0066_gmarketnewadproductcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketAdStrategySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='L코드 도매마트 전략', max_length=100)),
                ('accounts', models.JSONField(blank=True, default=list)),
                ('on_start', models.IntegerField(default=8)),
                ('on_end', models.IntegerField(default=16)),
                ('weekdays', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gmarket_ad_strategy_schedule',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GmarketAdGroupLcodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_index=True, max_length=50)),
                ('group_name', models.CharField(max_length=255)),
                ('product_nos', models.JSONField(blank=True, default=list)),
                ('seller_codes', models.JSONField(blank=True, default=list)),
                ('has_lcode', models.BooleanField(db_index=True, default=False)),
                ('strategy_applied', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gmarket_adgroup_lcode_status',
                'indexes': [models.Index(fields=['login_id', 'has_lcode'], name='gmarket_adg_login_i_a8b1f6_idx')],
                'unique_together': {('login_id', 'group_name')},
            },
        ),
    ]
