# Generated by Django 5.1.15 on 2026-09-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0067_gmarketadstrategyschedule_gmarketadgrouplcodestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmarketNewAdKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_index=True, max_length=50)),
                ('product_no', models.CharField(db_index=True, max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('keyword', models.CharField(max_length=255)),
                ('campaign_name', models.CharField(blank=True, default='', max_length=255)),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('avg_click_cost', models.BigIntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('conv_amount', models.BigIntegerField(default=0)),
                ('conv_count', models.IntegerField(default=0)),
                ('roas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gmarket_newad_keyword',
                'indexes': [models.Index(fields=['login_id', 'product_no'], name='gmarket_new_login_i_8dfab9_idx')],
                'constraints': [models.UniqueConstraint(fields=('login_id', 'product_no', 'keyword', 'period_start', 'period_end'), name='uniq_newad_keyword_login_product_keyword_period')],
            },
        ),
    ]
