# Generated by Django 5.1.15 on 2026-09-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0068_gmarketnewadkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomemartOrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order_no', models.CharField(max_length=50, unique=True)),
                ('product_name', models.TextField(blank=True, default='')),
                ('receiver_mobile', models.CharField(blank=True, default='', max_length=30)),
                ('courier', models.CharField(blank=True, default='', max_length=50)),
                ('tracking_no', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'domemart_order_record',
                'ordering': ['-updated_at'],
            },
        ),
    ]
