# Generated by Django 5.1.15 on 2026-09-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0069_domemartorderrecord'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gmarketmyproduct',
            index=models.Index(fields=['status_type', 'account', 'market'], name='gmkt_my_status_acct_mkt_idx'),
        ),
    ]
