# Generated by Django 5.1.15 on 2026-09-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0070_gmkt_my_status_acct_mkt_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevensellerofficestat',
            name='ai_campaign',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
