# Generated by Django 5.1 on 2026-05-22 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naver_path', models.CharField(db_index=True, max_length=300)),
                ('market', models.CharField(max_length=20)),
                ('market_category_id', models.CharField(max_length=50)),
                ('market_category_path', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'speedgo_category_mapping',
                'unique_together': {('naver_path', 'market')},
            },
        ),
        migrations.CreateModel(
            name='SpeedgoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domemea_no', models.CharField(db_index=True, help_text='도매매 상품번호', max_length=50, unique=True)),
                ('original_name', models.CharField(help_text='도매매 원본 상품명 (이번 MVP는 그대로 사용)', max_length=500)),
                ('processed_name', models.CharField(blank=True, default='', help_text='가공된 상품명 (현재 비어있음 — 추후 LLM 적용)', max_length=500)),
                ('wholesale_price', models.IntegerField(default=0)),
                ('shipping_fee', models.IntegerField(default=0)),
                ('supplier', models.CharField(blank=True, default='', max_length=100)),
                ('main_image_url', models.TextField(blank=True, default='')),
                ('detail_url', models.TextField(blank=True, default='')),
                ('naver_category_path', models.CharField(blank=True, default='', help_text='네이버 1위 상품 카테고리 경로', max_length=300)),
                ('naver_top_product_url', models.TextField(blank=True, default='')),
                ('naver_matched_at', models.DateTimeField(blank=True, null=True)),
                ('market_categories', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('새로담김', '새로 담김'), ('이름가공완료', '상품명 가공 완료'), ('카테고리매칭', '카테고리 매칭 완료'), ('등록준비', '마켓 등록 준비'), ('등록완료', '마켓 등록 완료'), ('운영중', '운영 중'), ('보류', '보류'), ('삭제', '삭제됨')], default='새로담김', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'speedgo_item',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['status'], name='speedgo_ite_status_b9003b_idx'), models.Index(fields=['naver_category_path'], name='speedgo_ite_naver_c_03ed61_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpeedgoLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=30)),
                ('level', models.CharField(default='info', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='speedgo.speedgoitem')),
            ],
            options={
                'db_table': 'speedgo_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
