# Generated by Django 5.1 on 2026-07-02 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoupangAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100, unique=True)),
                ('login_pw', models.CharField(blank=True, default='', max_length=200)),
                ('seller_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_rocket_growth', models.BooleanField(default=False, help_text='로켓그로스 사용 계정 여부')),
                ('is_active', models.BooleanField(default=True)),
                ('cookie_data', models.TextField(blank=True, default='')),
                ('cookie_saved_at', models.DateTimeField(blank=True, null=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupang_account',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoupangVatSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('sale_type', models.CharField(choices=[('판매자윙', '판매자윙'), ('로켓그로스', '로켓그로스')], max_length=20)),
                ('credit_card', models.BigIntegerField(default=0)),
                ('cash_receipt', models.BigIntegerField(default=0)),
                ('etc_payment', models.BigIntegerField(default=0)),
                ('total_sales', models.BigIntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_sales', to='coupang.coupangaccount')),
            ],
            options={
                'db_table': 'coupang_vat_sales',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['account', 'year', 'month'], name='coupang_vat_account_d5be37_idx')],
                'unique_together': {('account', 'year', 'month', 'sale_type')},
            },
        ),
    ]
