# Generated by Django 5.1 on 2026-07-03 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupangaccount',
            name='access_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coupangaccount',
            name='api_key_expires_at',
            field=models.DateTimeField(blank=True, help_text='오픈API 키 유효기간', null=True),
        ),
        migrations.AddField(
            model_name='coupangaccount',
            name='secret_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coupangaccount',
            name='vendor_id',
            field=models.CharField(blank=True, default='', help_text='업체코드 (예: A01122552)', max_length=20),
        ),
        migrations.CreateModel(
            name='CoupangOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('shipment_box_id', models.CharField(blank=True, default='', max_length=50)),
                ('ordered_at', models.DateTimeField()),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('vendor_item_id', models.CharField(blank=True, default='', max_length=50)),
                ('seller_product_id', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('sales_price', models.BigIntegerField(default=0, help_text='주문 시 상품가격(1개 기준 orderPrice)')),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coupang.coupangaccount')),
            ],
            options={
                'db_table': 'coupang_order',
                'ordering': ['-ordered_at'],
                'indexes': [models.Index(fields=['account', 'ordered_at'], name='coupang_ord_account_baea8a_idx')],
                'unique_together': {('account', 'order_id', 'vendor_item_id')},
            },
        ),
    ]
