# Generated by Django 5.1 on 2026-07-03 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupang', '0002_coupangaccount_access_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupangProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('product_id', models.CharField(blank=True, default='', max_length=50)),
                ('category_id', models.CharField(blank=True, default='', max_length=50)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('status_name', models.CharField(blank=True, default='', help_text='승인완료/승인반려 등', max_length=30)),
                ('sale_started_at', models.DateTimeField(blank=True, null=True)),
                ('sale_ended_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='coupang.coupangaccount')),
            ],
            options={
                'db_table': 'coupang_product',
                'ordering': ['-registered_at'],
                'unique_together': {('account', 'seller_product_id')},
            },
        ),
    ]
