# Generated by Django 5.1 on 2026-08-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupang', '0003_coupangproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupangproduct',
            name='seller_product_code',
            field=models.CharField(blank=True, default='', help_text='판매자관리코드(items[].marketplaceItemData.externalVendorSku, W코드) — 상세조회API 필요, 목록API엔 없음', max_length=100),
        ),
    ]
