# Generated by Django 5.1 on 2026-04-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('row_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_upload_logs',
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(max_length=500)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('commission', models.IntegerField(default=0)),
                ('shipping_fee', models.IntegerField(default=0)),
                ('net_profit', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '대기'), ('completed', '완료'), ('cancelled', '취소'), ('returned', '반품')], default='completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='accounts.selleraccount')),
            ],
            options={
                'db_table': 'sales_records',
                'ordering': ['-order_date'],
            },
        ),
    ]
