# Generated by Django 5.1 on 2026-06-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesrecord_platform_salesrecord_shop_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
