# Generated by Django 5.1 on 2026-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesrecord_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='order_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
