# Generated by Django 5.1 on 2026-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0004_salesrecord_order_datetime'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['-order_date'], name='sales_recor_order_d_d7fddc_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['platform', 'order_date'], name='sales_recor_platfor_031092_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['status', 'order_date'], name='sales_recor_status_20b25d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['platform', 'status', 'order_date'], name='sales_recor_platfor_b7b7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['product_code'], name='sales_recor_product_358f5d_idx'),
        ),
    ]
